### ISSUE TITLE
mogptk from PyPI still requires pre-release version of GPFlow 2

### ISSUE THREAD

**Issue by jjramsey** [GAMES-UChile/mogptk#16]
There's a bit of an annoyance when installing mogptk from pip. It uninstalls the latest release of GPFlow 2 (v. 2.0.4 at the time of writing) and installs GPFlow 2.00rc1. Of course, I can fix this by upgrading GPFlow again, but I really shouldn't have to.

**Comment by tdewolff** [comment]
Thanks for the suggestion, we should really use the latest version of GPflow I agree! GPflow is a fast moving library and we had some problems with a previous version of GPflow 2. These problems should be fixed now so we can safely upgrade the required version. We'll upgrade soon after we've done some testing to see if everything works as expected.

**Comment by jjramsey** [comment]
Fixed in release 0.1.10.
