### ISSUE TITLE
Train mean function

### ISSUE THREAD

**Issue by j-faria** [GAMES-UChile/mogptk#18]
Can any of the models currently implemented have a user-defined mean function? 
If yes, can the mean function have trainable parameters (ideally per channel)?

Thank you.
This is a fantastic package, congratulations!

**Comment by tdewolff** [comment]
Hi João, thanks for the question! This is currently not possible, however if you're looking for a non-trainable mean function I suggest you subtract that mean function from your data first. You can use the `Transform*` functions such as `TransformDetrend`. If you want to make you mean function trainable such as in https://gpflow.readthedocs.io/en/master/notebooks/tailor/external-mean-function.html, this would need a trivial change in the MOGPTK library to pass `mean_function` to the `GPR` model or any other model. We will look into this!

**Comment by exponent96** [comment]
I hope this feature can be implemented soon!

**Comment by tdewolff** [comment]
Yes! We're working very hard on a new version (that will be based on PyTorch by the way) that will support this feature! Please stay advised, we hope to release within a months time.

**Comment by tdewolff** [comment]
We've released v0.2.0 (install from `pip`) that contains a migration to PyTorch. Please see [06 Custom Kernels and Mean Functions](https://github.com/GAMES-UChile/mogptk/blob/master/examples/06_Custom_Kernels_and_Mean_Functions.ipynb) for an example on training a mean function. You can pass a mean function to the MOGP models with v0.2.1, let me know if that works. If you encounter problems please comment here or open a new issue!
