### ISSUE TITLE
Can this model use other kernels

### ISSUE THREAD

**Issue by NCLHILL** [GAMES-UChile/mogptk#23]
All the LMC and CONV kernel can only use the SM kernel inside, how can I use other kernels instead of SM kernel in SM-LMC?

**Comment by tdewolff** [comment]
Hi NCLHILL, thanks for reaching out! The models we have in https://github.com/GAMES-UChile/mogptk/tree/master/mogptk/models are really just a shell around the kernel with parameter initialization implemented. Surely, the initialization would be very different if you'd use another kernel, so you'll have to implement that yourself.

I suggest you copy the `__init__` function in https://github.com/GAMES-UChile/mogptk/blob/master/mogptk/models/sm_lmc.py and create a new class. You'll have to replace `spectral` on line 48 with another kernel you'd like to use. I suggest you keep the weight fixing for SM at line 62, as this will be handled by the weights in the LMC kernel. Please let me know if you need more help!

**Comment by NCLHILL** [comment]
Dear Taco,

 

Many thanks for your help. I was trying to change the SM kernel to RQ kernel in your code. However, when I change the line 48 and 62 as you said. The code still has some problem in the init_parameters, it seems like there is no means and variances in the RQ kernel? Pycharm always said AttributeError: 'RationalQuadraticKernel' object has no attribute 'mean'. Please see the red box in the follow Fig. May I ask how can I rewrite the init_parameters part to suitable for other kernel, like RQ kernel? Many thanks.

 



 

Best regards,

Jiangjiao

**Comment by tdewolff** [comment]
Yes, the code in `init_parameters` is very specific for the SM-LMC kernel. If you're using an RQ-LMC kernel you'll need to rewrite the `init_parameters` function, or forget about it and start with random kernel parameters. I'm unaware of methods to initialize the RQ kernel, but surely there must be literature about this subject! If you happen to find more information we'd be happy if you'd share it here, perhaps we can incorporate it in the library.

**Comment by NCLHILL** [comment]
Hi Taco,

I am trying to increase the data range to more than 2000. When the data points are less than 2000, the program works well. However, when I apply 2016 data points for each task. At the gpr/model/GPR log_marginal_likelihood stage, the output of 'K matrix' turn to Nan. Do you have any idea what happened?

**Comment by tdewolff** [comment]
You might be hitting a numerical precision error, which is quite possible
with GPs. Could you please try with a different model initialization? Are
you saying that the values of your input data (X) is in the range of
0--2016, or that you have 2016 data points? If it's the former, please try
and rescale/normalize your data before input. Let me know how that goes!

Saludos cordiales,
Taco de Wolff

**Comment by NCLHILL** [comment]
I have three tasks and each task has 2016 datapoints. When I reduce the datapoints to 2000 for each task. It does work! However, if I try to increase the data points from 2000 to 2016, even 2002 points for each task. The output ‘K’ matrix is nan. I have checked the ‘class GPR(Model) def log_marginal_likelihood’ in ‘gpr/model’. The problem is that ‘self.kernel(self.X)’ is nan. When I try to get inside of self.kernel. I found that problem is the ‘self.mean()’ turns to nan. You can try any sample over 2000 datapoints in turn to nan. 

 

I have also tried with a model initialization, it works. However, when I delete the ‘model.init_parameters(method='LS')’ step, it failed. It seems that I have to use the model.init_parameters. If I try to use other kernels without model.init_parameters. It will show the error again with nan matrix of ‘K’. Is there any idea that can fix this problem? 

 

Thanks.

**Comment by tdewolff** [comment]
By default, the model's mean is set to `None`, as in it is disabled. Do you set the `mean` when initializing a model, as in `MOSM(..., mean=something)`? It appears that that `something` is returning `NaN` if I understand your problem correctly. If there is no `mean` set for the model, it will never call `self.mean` inside `GPR`. Please let me know what mean function you're passing, or please share a snippet of your code so I can take a look myself.

**Comment by tdewolff** [comment]
Please reopen if you still have this issue, I'm assuming this is fixed by now.
