### ISSUE TITLE
Support for when dim(X)>1?

### ISSUE THREAD

**Issue by jimmyrisk** [GAMES-UChile/mogptk#24]
Hi,

I just found this package and it's amazingly clean which I really like.

However, I'm not finding much on how to implement anything for when dim(X)>1.  

As an example, my data set is mortality related, with two inputs (age, calendar year).  It's useful to be able to predict annually (one year ahead) so for example, given a data set for ages [50,85] and calendar years [1990,2018], I may want to leave out 2018 for prediction assessment.

On a similar note, is there any 1d plotting functionality?  For example, could I fix the year to be 2018, and put age (in [50, 85]) on the x axis?  Or, for a fixed age, plot mortality rates with year on the x axis?

If there are any examples or documentation how to do this, please send me in that direction (I cannot find any right now).

Best,
Jimmy

**Comment by tdewolff** [comment]
Hi Jimmy, thanks for the feedback! The library should be able to train with more than one input dimension, unfortunately there is not an example right now showcasing that. Basically, all functions in `Data` and `Dataset` should be able to handle multiple input dimensions by passing arrays instead of values. The `LoadCSV` and `LoadDataframe` support loading multiple input dimensions  as well. The only thing missing is plotting functionality, which you mentioned, including plotting 2D or 3D graphs and marginal distributions, i.e. plotting a 1D graph for a 2D dataset by fixing one axis. This is not trivial at all, which is why we have it on our (future) todo list in #2, for now you'll have to manually implement that for your specific use case. Please let us know if training or data manipulation shows problems with >1D data sets!

**Comment by jimmyrisk** [comment]
Thanks for the quick reply!

It was actually incredibly easy to train the model.  My question is regards to labelling data for leave out testing purposes, which seems to only work when dim(X)=1.

I believe I could hand-code a way to handle other things (prediction, plotting, etc.), but it would be nice to be able to utilize the built-in test set code for prediction purposes.

For reference, my X is a mogptk DataFrame with columns "age" and "calendar year".  If I try to use ``remove_range``, it looks something like this:

```
for i, channel in enumerate(mortData):
    channel.remove_range('2017-11-17', None)
Traceback (most recent call last):
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\IPython\core\interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-48767bb2aae4>", line 2, in <module>
    channel.remove_range('2017-11-17', None)
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\data.py", line 566, in remove_range
    raise ValueError("can only remove ranges on one dimensional input data")
ValueError: can only remove ranges on one dimensional input data
```

Obviously this will give an error from the perspective of it not knowing what column I want to remove the range from, but regardless, this error is suggesting to me that there's not a way to utilize ``remove_range`` to handle my task.  Is there a functionality I'm missing, or an easy workaround?

**Comment by tdewolff** [comment]
Yes, I'll try and work on a solution, probably next week

**Comment by tdewolff** [comment]
Actually got to it just now, please report if it works correctly. Note that the library lacks multi input dimension support in much of the `Data` class yet.

**Comment by jimmyrisk** [comment]
Thank you so much for the prompt response!  It does work.

**Comment by tdewolff** [comment]
I've further improved support for `1 < input_dims` in the code with https://github.com/GAMES-UChile/mogptk/commit/d51c59c285a29aadf894cac8e4bdda0a169591ea, https://github.com/GAMES-UChile/mogptk/commit/751975a250ae0b99478d01164f72a528020ddf8f, and https://github.com/GAMES-UChile/mogptk/commit/16ecf9649a0a6d694e1a4d00cc624afd11a0a195. I haven't had time to check all the new functionality fully, but by the looks it seems to work. Let me know if you git any bumps ;-)

**Comment by SGH-188** [comment]
> 感谢您的快速回复！
> 
> 训练模型实际上非常容易。我的问题是关于为遗漏测试目的标记数据，这似乎只在 dim(X)=1 时有效。
> 
> 我相信我可以手动编写一种方法来处理其他事情（预测、绘图等），但是能够利用内置的测试集代码进行预测会很好。
> 
> 作为参考，我的 X 是一个 mogptk 数据框，其中包含“年龄”和“日历年”列。如果我尝试使用`remove_range`，它看起来像这样：
> 
> ```
> for i, channel in enumerate(mortData):
>     channel.remove_range('2017-11-17', None)
> Traceback (most recent call last):
>   File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\IPython\core\interactiveshell.py", line 3427, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-3-48767bb2aae4>", line 2, in <module>
>     channel.remove_range('2017-11-17', None)
>   File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\data.py", line 566, in remove_range
>     raise ValueError("can only remove ranges on one dimensional input data")
> ValueError: can only remove ranges on one dimensional input data
> ```
> 
> 显然，从不知道我想从哪个列中删除范围的角度来看，这会给出一个错误，但无论如何，这个错误向我暗示，没有一种方法可以`remove_range`用来处理我的任务。是否有我缺少的功能或简单的解决方法？


Hi, jimmyrisk, I'm not finding much on how to implement anything for when dim(X)>1,too. However, you said It was actually incredibly easy to train the model. Do you mean when dim(X)>2?, If so, can you spare me your advice or example?

Best,
GHS

**Comment by SGH-188** [comment]
> Thanks for the quick reply!
> 
> It was actually incredibly easy to train the model. My question is regards to labelling data for leave out testing purposes, which seems to only work when dim(X)=1.
> 
> I believe I could hand-code a way to handle other things (prediction, plotting, etc.), but it would be nice to be able to utilize the built-in test set code for prediction purposes.
> 
> For reference, my X is a mogptk DataFrame with columns "age" and "calendar year". If I try to use `remove_range`, it looks something like this:
> 
> ```
> for i, channel in enumerate(mortData):
>     channel.remove_range('2017-11-17', None)
> Traceback (most recent call last):
>   File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\IPython\core\interactiveshell.py", line 3427, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
>   File "<ipython-input-3-48767bb2aae4>", line 2, in <module>
>     channel.remove_range('2017-11-17', None)
>   File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\data.py", line 566, in remove_range
>     raise ValueError("can only remove ranges on one dimensional input data")
> ValueError: can only remove ranges on one dimensional input data
> ```
> 
> Obviously this will give an error from the perspective of it not knowing what column I want to remove the range from, but regardless, this error is suggesting to me that there's not a way to utilize `remove_range` to handle my task. Is there a functionality I'm missing, or an easy workaround?

Hi, jimmyrisk, I'm not finding much on how to implement anything for when dim(X)>1,too. However, you said It was actually incredibly easy to train the model. Do you mean when dim(X)>2?, If so, can you spare me your advice or example?

Best,
GHS

**Comment by SGH-188** [comment]
> Hi Jimmy, thanks for the feedback! The library should be able to train with more than one input dimension, unfortunately there is not an example right now showcasing that. Basically, all functions in `Data` and `Dataset` should be able to handle multiple input dimensions by passing arrays instead of values. The `LoadCSV` and `LoadDataframe` support loading multiple input dimensions as well. The only thing missing is plotting functionality, which you mentioned, including plotting 2D or 3D graphs and marginal distributions, i.e. plotting a 1D graph for a 2D dataset by fixing one axis. This is not trivial at all, which is why we have it on our (future) todo list in #2, for now you'll have to manually implement that for your specific use case. Please let us know if training or data manipulation shows problems with >1D data sets!

Hi, tdewolff. Like Jimmy, I'm not finding much on how to implement anything for when dim(X)>1,too. You say the library should be able to train with more than one input dimension, please send me any examples or documentation how to do this.
Thank you very much
Best,
GHS

**Comment by tdewolff** [comment]
As I responded to you privately, I've uploaded an example of using multi-input datasets with MOGPTK here: https://games-uchile.github.io/mogptk/examples.html?q=07_Multi_Input

Please be aware that you need to update to the latest version from the repository. That is, you have to do a `git pull` and make sure to deinstall the toolkit `pip uninstall mogptk` and then install from the mogptk directory as `pip install --upgrade -e .`. Please let me know if you have any questions!
