### ISSUE TITLE
Sigmoid Backward

### ISSUE THREAD

**Issue by ssydasheng** [GAMES-UChile/mogptk#25]
Hi, should the backward be  `y = (y - self.lower) / (self.upper - self.lower)` ? 

https://github.com/GAMES-UChile/mogptk/blob/95b2c6c83d523eb5f7da0142efaf12ec71877212/mogptk/gpr/parameter.py#L40

**Comment by tdewolff** [comment]
Yes you are right, this should be fixed now, thank you!
