### ISSUE TITLE
"RuntimeError: CUDA out of memory" Occurring in MOGPTK, not in GPyTorch

### ISSUE THREAD

**Issue by jimmyrisk** [GAMES-UChile/mogptk#29]
When I fit a LMC to my data set using GPyTorch, I have no issues, but when I try to fit the same model using MOGPTK, I have a memory error. I understand this is a different package than GPyTorch, but given the common use of Torch, I would expect it to work without any memory issues.

Here is the error I am obtaining, after running ``model.train(...)``:

```
Starting optimization using Adam
‣ Model: SM-LMC
‣ Channels: 10
‣ Mixtures: 6
‣ Training points: 20
‣ Parameters: 94
Traceback (most recent call last):
  File "<input>", line 4, in <module>
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\model.py", line 224, in train
    print('‣ Initial loss: {:.3g}'.format(self.loss()))
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\model.py", line 144, in loss
    return self.model.loss().detach().cpu().item()
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\model.py", line 182, in loss
    loss = -self.log_marginal_likelihood() - self.log_prior()
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\model.py", line 219, in log_marginal_likelihood
    K = self.kernel(self.X) + self.noise()*torch.eye(self.X.shape[0], device=config.device, dtype=config.dtype)  # NxN
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\kernel.py", line 17, in __call__
    return self.K(X1,X2)
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\kernel.py", line 169, in K
    k = self.Ksub(i, j, x1[i], x1[j])
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\multioutput.py", line 127, in Ksub
    kernels = torch.stack([kernel(X1,X2) for kernel in self.kernels], dim=2)  # NxMxQ
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\multioutput.py", line 127, in <listcomp>
    kernels = torch.stack([kernel(X1,X2) for kernel in self.kernels], dim=2)  # NxMxQ
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\kernel.py", line 17, in __call__
    return self.K(X1,X2)
  File "C:\Users\jrisk\anaconda3\envs\gp-mort\lib\site-packages\mogptk\gpr\singleoutput.py", line 134, in K
    return self.weight() * torch.prod(exp * cos, dim=2)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 11.00 GiB total capacity; 8.21 GiB already allocated; 18.70 MiB free; 8.70 GiB reserved in total by PyTorch)
```

It's worth noting that this works without issue when there are 4 channels (instead of 10).  I tried 6 channels but had the same memory issue.  It also occurred when trying MOSM.

Here is my full code.  I can't quite provide a reproducible example yet.  For reference, ``mort`` is a data frame with 1015 rows and 12 columns (two predictors, and ten responses (corresponding to the channels)).

```
import numpy as np
from matplotlib import pyplot as plt
from HMD_data import getMortData_new
import mogptk

countries = ["'CAN'", "'NOR'" , "'AUS'", "'BLR'", "'USA'"]
mort = getMortData_new(countries)

x_names = list(mort.columns[0:2])
y_names = list(mort.columns[2:])
mortData = mogptk.LoadDataFrame(mort, x_col = x_names, y_col = y_names)
mortData.transform(mogptk.TransformStandard())

rem_start = [0, 2016]
rem_end = [0, 2018]

for i, channel in enumerate(mortData):
    channel.remove_range(rem_start, rem_end)
    #channel.transform(mogptk.TransformDetrend(degree=1))
    channel.transform(mogptk.TransformNormalize())

modelMOSM = mogptk.MOSM(mortData, Q=6)
modelMOSM.init_parameters()
modelMOSM.train(iters=2000, verbose=True, plot=True, error='MAE')
```

``modelMOSM.init_parameters()`` seems to work fine.

Side note: is ``training points=20`` accurate??  ``MortData`` has 1015 rows...

**Comment by tdewolff** [comment]
Could you try and use `torch.cuda.empty_cache()` after `init_parameters`? This may free up some memory, the default parameter initializer is pretty slow and memory hungry (BNSE), you could try and use `init_parameter(method='LS')` instead as well.

As to memory usage, from some simple testing I'm not seeing anything strange happening in training a simple SM model with 10 data points for 100 iterations with Adam. It was actually consuming LESS memory than GPyTorch (6MB vs 9.7MB). Still there may be a chance to further optimize, especially the multi-output kernel has a large `torch.empty` (e.g. https://github.com/GAMES-UChile/mogptk/blob/master/mogptk/gpr/kernel.py#L182) that could perhaps be reused some way. This problem may be more apparent with larger data sets.

In any case, the implementation of GPyTorch is really different w.r.t. multi channels (if they haven't changed in the meantime) which requires significantly less memory. MOGPTK build up a large covariance matrix (K) comprised of all smaller covariance matrices for each of the channel combinations. This large K may be a problem, but there isn't much to do about that I'm afraid. I'll run some more tests and let you know if I find anything, thanks!

**Comment by tdewolff** [comment]
Could you prepare two experiments that are equivalent for both MOGPTK and GPyTorch? I suppose you already did this, reading your post. Can you send me the source so I can execute both and measure their performance? The memory profiler should show us the problem hopefully!

**Comment by jimmyrisk** [comment]
Apologies for the late reply, I've been busy with some teaching stuff.  I'm attaching two python files along with the .csv that should hopefully highlight the issue.  

Here is the working example for gpytorch (works fine)

```
import torch
import gpytorch
from gpytorch.kernels import MaternKernel
import pandas as pd

device = torch.device('cuda:0')

def df_to_tensor(df):
    return torch.from_numpy(df.values).float().to(device)

mort = pd.read_csv("c:/data/mortdata.csv")

train_x_raw = mort[["age", "yr"]]
train_x = df_to_tensor(train_x_raw)  # automatically converts to CUDA

train_y_Stacked = torch.empty(10,1015).cuda()
i = 0

for column in mort.columns[3:]:
    tensor = mort[column]
    train_y_Stacked[i] = torch.tensor(tensor).cuda()
    i += 1


latent_kernels = [MaternKernel(nu=2.5, ard_num_dims=2),
                  MaternKernel(nu=2.5, ard_num_dims=2),
                  MaternKernel(nu=2.5, ard_num_dims=2),
                  MaternKernel(nu=2.5, ard_num_dims=2)]

rank = 1  # duplicates kernels for value of rank.
# use rank=1 to control latent factors only through latent_kernels
rankk = 0
D=10

class MultitaskGPModel(gpytorch.models.ExactGP):
    def __init__(self, train_x, train_y, likelihood, D, rank, kernels):
        super(MultitaskGPModel, self).__init__(train_x, train_y, likelihood)
        self.mean_module = gpytorch.means.MultitaskMean(
            gpytorch.means.ZeroMean(), num_tasks=D
        )
        self.covar_module = gpytorch.kernels.LCMKernel(
            kernels, num_tasks=D, rank=rank
        )

    def forward(self, x):
        mean_x = self.mean_module(x)
        covar_x = self.covar_module(x)
        return gpytorch.distributions.MultitaskMultivariateNormal(mean_x, covar_x)



likelihood = gpytorch.likelihoods.MultitaskGaussianLikelihood(num_tasks=D, rank=rankk,
                                                                      noise_constraint=gpytorch.constraints.GreaterThan(1e-3)).cuda()
model = MultitaskGPModel(train_x, train_y_Stacked, likelihood,
                                   D, rank, latent_kernels).cuda()

model.train()
likelihood.train()

# "Loss" for GPs - the marginal log likelihood
mll = gpytorch.mlls.ExactMarginalLogLikelihood(likelihood, model).cuda()

optimizer = torch.optim.Adam(model.parameters(), lr=0.1)  # Includes GaussianLikelihood parameters

training_iterations = 50

for i in range(training_iterations):
    optimizer.zero_grad()
    output = model(train_x)
    loss = -mll(output, train_y_Stacked)
    loss.backward()
    optimizer.step()
    print(
        'Iter %d/%d - Loss: %.3f' % (i + 1, training_iterations, loss.item()))
```


Here is the code for the mogptk example which gives a memory error:

```
import mogptk
import pandas as pd

mort = pd.read_csv("c:/data/mortdata.csv")


x_names = list(mort.columns[0:2])
y_names = list(mort.columns[2:])
mortData = mogptk.LoadDataFrame(mort, x_col = x_names, y_col = y_names)
mortData.transform(mogptk.TransformStandard())

rem_start = [0, 2016]
rem_end = [0, 2018]

for i, channel in enumerate(mortData):
    channel.remove_range(rem_start, rem_end)  # remove years 2016 to 2018
    #channel.transform(mogptk.TransformDetrend(degree=1))
    channel.transform(mogptk.TransformNormalize())

modelSM_LMC = mogptk.SM_LMC(mortData, Q=6)
modelSM_LMC.init_parameters()
modelSM_LMC.train(iters=2000, verbose=True, plot=True, error='MAE')

```

You need to change the file path of ``mortdata.csv``.  Also, it won't let me upload it here, so here is a [direct link](https://livecsupomona-my.sharepoint.com/:x:/g/personal/jrisk_cpp_edu/EWLx1M8rgM9HqVDGXr6ds90BiPQ3CebXDEbxo_2PHei9lQ?e=taQBX2).

**Comment by tdewolff** [comment]
Thanks Jimmy, we will look into it and report back to you!

**Comment by jimmyrisk** [comment]
Sorry on my end for responding late, I have been busy with other projects as well.  It seems like you are correct -- I tried doing anything else with the model beyond training, including

```
model(train_x)

predictions = likelihood(model(test_x))  # test_x is significantly smaller sized test set

with torch.no_grad(), gpytorch.settings.fast_pred_var():
    predictions = likelihood(model(test_x))
```

and all of these give CUDA out of memory errors.  I'm a bit dumbfounded since I thought I had a working version before beyond model training - maybe it had something to do with the choices of Q and Rq.

If I can find a version that seems to work in GPyTorch and not in MOGPTK, I will let you know.  Thank you for looking into this.
