### ISSUE TITLE
multi-input and multi-output problem

### ISSUE THREAD

**Issue by Fangwq** [GAMES-UChile/mogptk#30]
It seems that this package is apt to solve one dimensional input, how can I code to solve multi-input and multi-output problem? for example,  the shape of input is (32, 64), and output is also (32, 64), after training, how to predict on the test data with shape (1, 64), would you like to share the demo to solve it?

**Comment by tdewolff** [comment]
We haven't had the time to properly create examples for this case, but this is a recent response we gave to another user:

Below a quick example of how to load a 2D data set, let me know if that works for you. If you have more questions, please let me know.

```
# create two input dimensions with 20 and 10 points repectively
n1 = 20
n2 = 10
x1 = np.linspace(0.0, 2.0, n1)
x2 = np.linspace(0.0, 1.0, n2)

# create an input matrix of shape (N, 2)
N = n1*n2
x = np.vstack([
    np.repeat(x1, n2),
    np.tile(x2, n1),
]).T

# create output data
y = np.sin(2.0*np.pi*x[:,0]) + 0.5*np.sin(2.0*np.pi*10.0*x[:,1]) + 0.1*np.random.randn(N)

# load data set
dataset = mogptk.DataSet(
    mogptk.Data(x, y),
)

method = 'adam'
iters = 250
mosm = mogptk.MOSM(dataset, Q=2)
mosm.init_parameters(method='ls')
mosm.train(method=method, iters=iters, verbose=True)
```

Be aware that plotting functionality doesn't support 2D input as of yet (we're working on it!).

**Comment by Fangwq** [comment]
This is not what I want, but thank you for your reply. I write a demo for my case: 
```
n_points = 32
dim = 128
t = np.random.rand(n_points, dim)
t = pd.DataFrame(t, columns=list(map(lambda x: str(x), list(range(dim)))))
dataset = mogptk.LoadDataFrame(t, x_col=list(map(lambda x: str(x), list(range(int(dim/2))))), \
                               y_col=list(map(lambda x: str(x), list(range(int(dim/2), dim)))))
print(dataset)
model = mogptk.MOSM(dataset, Q=64)
model.init_parameters('BNSE')
model.train(method='Adam', lr=0.5, iters=1, verbose=True)
print(model.predict())
```
Then, the question is how to do prediction for test data with shape (1, 64)?

**Comment by Gullen-Sw** [comment]
I have the same question, and I try to solve by myself but I fail to deal with, so I want to get some advice for this case.
is there anyone who could reach the goal?

**Comment by tdewolff** [comment]
@Fangwq for a DataFrame it is much easier. You're in the right direction, just that `predict` doesn't return a value and instead saves its results for plotting later on. The model is already predicting! For an example with less dimensions:

```python
import numpy as np
import pandas as pd
import mogptk

n_points = 32
x_dims = 2
y_dims = 4
t = np.random.rand(n_points, x_dims+y_dims)
t = pd.DataFrame(t)

dataset = mogptk.LoadDataFrame(
    t,
    x_col=list(range(0,x_dims)),
    y_col=list(range(x_dims, x_dims+y_dims)),
)

model = mogptk.MOSM(dataset, Q=10)
model.init_parameters('BNSE')
model.train(method='Adam', lr=0.5, iters=1, verbose=True)
print(model.predict())
```

In order to change the prediction range, use the `Data.set_prediction_range` or `Data.set_prediction_x` functions. The same functions for `DataSet` require the same parameters, each being a list with items for each output dimension which are passed to each channel's underlying `Data`.

```python
# dataset has 4 output channels, and 2 input dimensions
dataset.set_prediction_range(start=[[0,0], [0,0], [0,0], [0,0]], end=[[1,1], [1,1], [1,1], [1,1]], n=[[10,10], [10,10], [10,10], [10,10]])

# which is the same as
dataset.set_prediction_range(start=0, end=1, n=10)

# and explicitly
dataset.set_prediction_x([[np.linspace(0.0, 1.0, 10) for i in range(x_dims)] for j in range(y_dims)])
```

I hope that also clears it up for you @Gullen-Sw ? Let me know if you have any further questions!

**Comment by Fangwq** [comment]
@tdewolff, Thanks for your clarification, and I will try it.

**Comment by tdewolff** [comment]
Assuming this has been resolved, please open a new issue or re-open this one if you still have problems!
