### ISSUE TITLE
get_parameters() not returning anything

### ISSUE THREAD

**Issue by ff1201** [GAMES-UChile/mogptk#38]
I'm trying to extract my parameters from a model, but the get_parameters() command doesn't seem to do anything. Here's an example using one of the given examples:

```
n_points = 500
frequencies = [0.2, 1.0, 2.0]
amplitudes = [1.0, 0.5, 0.5]

t = np.linspace(0.0, 20.0, n_points)
y = np.zeros(n_points)
for i in range(3):
    y += amplitudes[i] * np.sin(2.0*np.pi * frequencies[i] * t)
y += np.random.normal(scale=0.4, size=n_points)

# data class
data = mogptk.Data(t, y)
data.remove_range(start=10.0)
data.plot();

model = mogptk.SM(data, Q=3)
model.predict()

# initialize params
method = 'BNSE'
# method = 'LS'
# method = 'IPS'

model.init_parameters(method=method)
model.predict()
model.train(iters=100, lr=0.5, verbose=True)
model.predict()

params = model.get_parameters()
```

I can print the parameters fine, but I haven't found a way to extract the information. The get_parameters() function generates a NoneType variable with no values.

**Comment by tdewolff** [comment]
Thanks for raising the issue, this should now be fixed on `master`, please let me know if it works for you!

**Comment by ff1201** [comment]
It works, thanks a lot for fixing!

**Comment by ff1201** [comment]
Is it possible to extract the values into a variable? The get_parameters() function returns a list of the parameters. Taking any item in the list gives us a mogptk.gpr.parameter.Parameter object, but from here I don't see any attribute of this class that gives the actual values.
