### ISSUE TITLE
Multiple trials in mogptk?

### ISSUE THREAD

**Issue by rlloretb** [GAMES-UChile/mogptk#52]
Is it possible to model in mogptk a Gaussian process which is observed multiple times?
Think of it as multiple trajectories coming from the same individual (multiple trials).
And what about hierarchical GPs?

**Comment by tdewolff** [comment]
Hi Roger, thank you for using MOGPTK. You can sample from the model to get
multiple draws from the GP if that is what you mean. Hierarchical GPs are
not explicitly supported yet, I can see if we could include that in the
future, thanks!

**Comment by rlloretb** [comment]
With "observed multiple times" I wanted to mean multiple realizations of the same gaussian process.

**Comment by tdewolff** [comment]
That is what I meant as well with sampling, it samples new realizations
from the same GP. Does this not work for you the way you think it should?

**Comment by tdewolff** [comment]
Closing this, please re-open if you have further questions.
