### ISSUE TITLE
non-time series use cases?

### ISSUE THREAD

**Issue by rowlesmr** [GAMES-UChile/mogptk#55]
The readme says
>The toolkit is mainly targeted to time-series, and includes plotting functions for the case of single input with multiple outputs (time series with several channels).

Is this package also good to deal with non-time series data?

In my case, I have spectral data with an accompanying vector of results I'd like to predict*. We're currently using many single-output GPs (in MATLAB), but would like to use multiple-output, as the outputs are correlated. Essentially, I want to train on spectral data, and then feed in a new spectrum and get back new results.

We have several hundred to several thousand training data sets, and about 10 values to predict. Each spectrum is (natively) 2966 points.

.

\* ie the training data is {(_x_<sub>_i_</sub>, _y_<sub>_i_</sub>); _i_=1.._N_}, with _x_<sub>_i_</sub> ∈ ℝ<sup>_d_</sup>, _y_<sub>_i_</sub> ∈ ℝ<sup>_e_</sup>, _d_ > _e_. I want to input _x_<sub>new</sub> and get back _y_<sub>new</sub>

**Comment by tdewolff** [comment]
It should work with any regular space, including time or spatial series. I suppose that spectral data could be fit with a regular GP, but fitting a kernel using the fact that it is spectral data is probably more efficient. This is actually what we do with the BNSE initialization method, see https://papers.nips.cc/paper_files/paper/2018/hash/abd1c782880cc59759f4112fda0b8f98-Abstract.html and the implementation at https://github.com/GAMES-UChile/mogptk/blob/master/mogptk/init.py.

**Comment by rowlesmr** [comment]
I'm falling over at the first hurdle, as I can't even figure out how to load my data.

My data consists of several hundred to several thousand lots of a ~3000 point spectrum associated with ~10 composition values. I want to feed in a new spectrum and get back 10 new compsition values.

From the docs, Data(X, Y) creates the data for training, where X is the independent variable and Y is the dependent variable (which I assume is cm^-1 vs intensity, in my case). Where do I input the composition values?

**Comment by tdewolff** [comment]
Not sure I follow what you mean with composition values. Let me summarize what I think I understood: you have 100-1000 data sets, each composed of 10 spectra at different wavelengths each having 3000 values. Is that correct?

The `Data(X,Y)` accepts inputs of shape `X: (num_points, input_dims)` and `Y: (num_points,)`. This means that in your case you have one input dimension (the frequency) and 10 output dimensions (the 10 components), each having approx. 300 points. You would load each components as `Data(X,Y)` with `X` and `Y` simple arrays of length `3000` of the frequencies and spectral values respectively. Then load the 10 `Data` objects into a `DataSet(Data, Data, ...)`. This will create a multi-output dataset that you can fit. You can fit this for each of your 100-1000 data sets. I hope that helps...

**Comment by rowlesmr** [comment]
The gaussian process regression in matlab is setup to predict a scalar variable from an associated vector of variables. It (and I) don't care about the xordinate value, as it is essentially just a channel number)

From the matlab help, an input set might look like:

```
[[ 0.455, 0.365, 0.095,  0.514, 0.2245,  0.101,  0.15], 15]  
[[  0.35, 0.265,  0.09, 0.2255, 0.0995, 0.0485,  0.07],  7]  
[[  0.53,  0.42, 0.135,  0.677, 0.2565, 0.1415,  0.21],  9]  
[[  0.44, 0.365, 0.125,  0.516, 0.2155,  0.114, 0.155], 10]  
[[ 0.425,   0.3, 0.095, 0.3515,  0.141, 0.0775,  0.12],  8]  
[[  0.53, 0.415,  0.15, 0.7775,  0.237, 0.1415,  0.33], 20]
... #continue for many hundreds/thousands of rows
```
where each row is an individual training dataset, the first element in the list is a list of predictor values (eg the spectral intensities), and the second element in the list is the response variable (eg the composition value I want to predict from the given input. 

Once the model is trained, I then feed it a new input, and get back a new output:

```
[  0.33, 0.255,  0.08,  0.205, 0.0895, 0.0395, 0.055]
```
could return `7`.

.

I want to be able to predict multiple response variables.

**Comment by rowlesmr** [comment]
Yes, this is how I need to use it. I think I had fundamentally misunderstood how the input dimensions worked.

**Comment by rowlesmr** [comment]
Do you have any ideas on how Matlab implements GPR? in particular, their inference model? MOGPTK is significantly slower and the predictions are way off.

I've only been playing with MOGPTK for a few hours, and need to find the different options for everything, and figure out your nomenclature, so I may be barking at the wrong forest.

As far as I can tell (apart from the inference model) I think I'm reproducing the following matlab call:
```
model = fitrgp(predictors, response, 'KernelFunction','matern52', 'Standardize', true, 'Verbose', 1); 
%converges in ~18 s.
%predictors - 3522x2966 table
%response  - 3522x1 table
```

```
import mogptk
import numpy as np
mogptk.gpr.use_single_precision()

data = mogptk.LoadCSV("data.csv", x_col=predictors, y_col=responses, names=columns)
data.transform(mogptk.TransformNormalize())

#len(x_col) == 2966
#len(y_col) == 1  #I'm just trying to get my head around things first)
# num training points == 3522

kernel = mogptk.gpr.MaternKernel(nu=2.5)
inference = mogptk.Titsias(inducing_points=100, init_inducing_points='random')
model = mogptk.Model(data, kernel, inference=inference)

model_train = model.train(method = "Adam", iters=100, verbose=True, lr=10.0)  
# takes ~5 min, min loss ~3100
# I've tried a few iterations at lr=100, then 10 then 1, and a few other combinations.
model.plot_losses();

Xnew = np.asarray([[63.4, ...], [19.79, ...], [48.09, ...]])
model.predict(Xnew)

# The three results arrays from predict give the same answer for all three Xnews.
array([33.675, 33.675, 33.675], dtype=float32),
 array([-4.971292, -4.971292, -4.971292], dtype=float32),
 array([72.3213, 72.3213, 72.3213], dtype=float32))
```

**Comment by rowlesmr** [comment]
Thanks for your reply. Some responses below. I'll keep at it tomorrow.

> the x_col and y_col need to be names (strings) of the columns, not the data tables themselves. 
They are.

> the input needs to be of shape `N x input_dims` and the output as `N x 1`. If your X is of length 2966, that means you have 2966 training points. It should be 1x2966. Your Y is correct as shape 1 (same as 1x1). Number of training points is then 1, not 3522 
I've got 3522 datasets consisting of 2966 predictors/input dimensions and 1 response/output dimension

  - it is clear that your kernel is not training, you can try and see `model.print_parameters()` and note that while training the parameters get stuck most likely. 

> I don't know the Matlab implementation, but it probably has some sensible initial parameter estimation before training the GP. This is not implemented for MOGPTK for that specific kernel, but you should manually initialize the kernel parameters to reasonable estimates, otherwise training gets stuck in local minima 
I'll see if the matlab kernel params can be directly input into mogptk. Would the ARD kernel help in this case? The matlab help says "Because the GPR model uses an ARD kernel with many predictors, using an LBFGS approximation to the Hessian is more memory efficient than storing the full Hessian matrix. " https://www.mathworks.com/help/stats/fitrgp.html#mw_3bed4be1-f064-43a9-9a8f-4f7abd6089df

> when checking performance, can you compare execution time divided by the number of iterations? I suppose that Matlab has much fewer iterations die to better parameter initialization, that makes it much faster. Are you using the GPU? 

I think there is about 100 iters for Matlab; it's just faster. I don't know re GPU. I'll [investigate](https://games-uchile.github.io/mogptk/gpr/config.html) tomorrow.


Thanks for your time.

**Comment by tdewolff** [comment]
Have you had time to look at this? I'd be interested to know what difference in parameter initialization has the Matlab implementation. And please, can you share the number of iterations and the total execution time for both the Matlab and the MOGPTK cases?
