### ISSUE TITLE
EEG docs error

### ISSUE THREAD

**Issue by rowlesmr** [GAMES-UChile/mogptk#56]
The EEG exampl in the documentation has a non-positive definite error in it.

https://games-uchile.github.io/mogptk/examples.html?q=example_eeg

**Comment by rowlesmr** [comment]
And I hit the same error sometime after iteration 144.

**Comment by tdewolff** [comment]
Yes this is a known issue of the `MOHSM` kernel described in https://github.com/GAMES-UChile/mogptk/issues/45, it is something we need to look at!
