### ISSUE TITLE
fitting multiple trials

### ISSUE THREAD

**Issue by weigcdsb** [GAMES-UChile/mogptk#65]
I just wonder if there's a easy way to use the package for multiple trials? 

Basically, I now have K trials and each trial has p outputs. 
Each trial is an instance (i.e. a sample) of a MOGP, but all these trials are described by1 MOGP. 

I guess there should be a very easy way to handel this, rather than writing my own loss function and optimize it...

**Comment by tdewolff** [comment]
Did you figure it out? Would you care to post how you did it for other people to learn as well?
