### ISSUE TITLE
Seeds in examples and tutorials

### ISSUE THREAD

**Issue by luca-brambilla** [GAMES-UChile/mogptk#68]
Hello!

I was trying to use the toolkit for the first time, but I am not able to reproduce the results presented in the documentation. Is there any way you could provide the various seeds you used to obtain those outputs?

Thank you!

Luca

**Comment by tdewolff** [comment]
Seeds have now been added with https://github.com/GAMES-UChile/mogptk/commit/60aea73510361cb7d2651924e80c4dcbbd6b8a96, let me know if you're still unable to reproduce results
