### ISSUE TITLE
Could not save the model in mogptk-0.5.1

### ISSUE THREAD

**Issue by woodwood2000** [GAMES-UChile/mogptk#71]
When I run the 00_Quick_Start notebook, I could not save the model.

`# save model`
`model.save('mosm_example')`

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/var/folders/w2/t_sszyl159v9592xx84sb4pc0000gp/T/ipykernel_65991/3931476465.py in <module>
      1 # save model
----> 2 model.save('mosm_example')

~/anaconda3/envs/mogptk/lib/python3.7/site-packages/mogptk/model.py in save(self, filename)
    334             pass
    335         with open(filename, 'wb') as w:
--> 336             pickle.dump(self, w)
    337 
    338     def log_marginal_likelihood(self):

~/anaconda3/envs/mogptk/lib/python3.7/site-packages/mogptk/gpr/model.py in __getstate__(self)
    130 
    131     def __getstate__(self):
--> 132         state = super().__getstate__()
    133         state['_modules'] = state['_modules'].copy()
    134         state['_modules'].pop('_compiled_forward', None)

AttributeError: 'super' object has no attribute '__getstate__'

**Comment by tdewolff** [comment]
This must be because of an older version of PyTorch. I've pushed a fix for Model, but perhaps for Parameter you will run into a similar issue. Can you try and install from the `master` branch, and let me know if that works?

```
pip uninstall mogptk
git clone https://github.com/GAMES-UChile/mogptk
cd mogptk
pip install -e .
```

**Comment by woodwood2000** [comment]
It works. Thank you!
